sudo: required
service:
  - docker

before_install:
  - docker build -t jsoundar22/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run jsoundar22/react-test npm test -- --coverage

after_success:
  - docker build -t jsoundar22/multi-client -f ./client
  - docker build -t jsoundar22/multi-nginx -f ./nginx
  - docker build -t jsoundar22/multi-server -f ./server
  - docker build -t jsoundar22/multi-worker -f ./worker
  # Login to docker CLI
  echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password=stdin
  # take those images and push them into docker hub
  - docker push jsoundar22/multi-client
  - docker push jsoundar22/multi-nginx
  - docker push jsoundar22/multi-server
  - docker push jsoundar22/multi-worker


